# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
    ]
