# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 14:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_auto_20170714_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventofinterest',
            name='seasonset',
            field=models.CharField(default='astronomical', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventofinterest',
            name='date',
            field=models.DateField(default=datetime.date(2000, 7, 15)),
        ),
    ]
