# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventofinterest',
            old_name='seasonset',
            new_name='calendar',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='mtype',
            new_name='message_type',
        ),
    ]
