# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0003_auto_20170714_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('mtype', models.CharField(choices=[('email', 'email')], max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convert.EventOfInterest')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
